/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // docs: {
  //   Changelog: [
  //     {
  //       type: 'doc',
  //       id: 'changelog',
  //     },
  //   ],
  //   // Add other sections as needed
  // },
  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'introduction-edaran-docusaurus',
    'doc1',
    
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [
        'tutorial-basics/doc4',
        'tutorial-basics/doc2',
        'tutorial-basics/doc3',
        'tutorial-basics/doc5',
        'tutorial-basics/doc7',
        'tutorial-basics/doc6'
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [
        'tutorial-extras/doc-version',
        'tutorial-extras/doc-translate',
      ],
    },
  ],

  apiSidebar: [
    'changelog-v1',
    {
      type: 'category',
      label: 'API',
      items: [
        'my-dictionary',
        'API/comments',
        'API/photos',
        'API/dog-photo',
        'API/recipe',
        'API/rick-and-morty',
        ],
    },
  ],

  markdownSidebar: [
    {
      type: 'category',
      label: 'Markdown',
      items: [
        'Markdown/TOC', 
        'Markdown/diagrams',
        'Markdown/math',
        'Markdown/MyReactPage',
        'admonition'
      ]
    },
  ]
   
};

export default sidebars;
